### ISSUE TITLE
Call one-way requester / responder from command line

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-transport#97]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-transport/issues/97)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
It currently isn't possible to call a service which has no request or one that has no response from the command line, because it requires that all fields are set.

**Comment by adlarkin** [comment]
@chapulina when testing this, did you find that one-way responders also gave the `Service call timed out` message? I have a one-way responder with the following callback:

``` c++
bool ServiceName(ignition::msgs::Empty &_resp)
{
  // do some work...

  _resp.set_unused(true);
  return true;
}
```
When I do what you mentioned above (setting `--reqtype ignition.msgs.Empty --req 'unused: false'`), it seems like my service is being called, but I still see the `Service call timed out` message. I don't understand why this is happening since my service has a response type, and the callback returns `true`. Can this message be ignored?

**Comment by chapulina** [comment]
> it seems like my service is being called, but I still see the Service call timed out message

Could it be because your response type is empty?

I just ran the [responser_no_input](https://github.com/ignitionrobotics/ign-transport/blob/main/example/responser_no_input.cc) example, and I get a response without a timeout like this:

```
$ ign service -s /quote --reqtype ignition.msgs.Empty --reptype ignition.msgs.StringMsg --timeout 2000 --req 'unused: false'
data: "This is it! This is the answer. It says here...that a bolt of lightning is going to strike the clock tower at precisely 10:04pm, next Saturday night! If...If we could somehow...harness this lightning...channel it...into the flux capacitor...it just might work. Next Saturday night, we\'re sending you back to the future!"
```

**Comment by adlarkin** [comment]
> Could it be because your response type is empty?

That seems to be the reason why - I changed to response type to a string, and I no longer received this message. Are there any plans to try and remove this message in the future, or should it just be something to keep in mind moving forward when calling services?

**Comment by caguero** [comment]
We should fix it but it's not in the critical path right now.

**Comment by adlarkin** [comment]
Just for the recored, I tried to call a service with no request and an empty response type in c++ code using [Request(...)](https://ignitionrobotics.org/api/transport/9.0/classignition_1_1transport_1_1Node.html#a1e37eb77cdb5c047b63216e385af1648) from the API, and it seems like the service call times out there as well (so it's not just a command line issue regarding services with no request and an empty response type).

**Comment by chapulina** [comment]
> call a service with no request and an empty response type in c++

Yeah I could also reproduce it with this diff:

<details><summary>diff</summary>
<p>

```diff
diff --git a/example/requester_no_input.cc b/example/requester_no_input.cc
index d85374c1..86c490a2 100644
--- a/example/requester_no_input.cc
+++ b/example/requester_no_input.cc
@@ -25,7 +25,7 @@ int main(int argc, char **argv)
   // Create a transport node.
   ignition::transport::Node node;
 
-  ignition::msgs::StringMsg rep;
+  ignition::msgs::Empty rep;
   bool result;
   unsigned int timeout = 5000;
 
@@ -35,7 +35,7 @@ int main(int argc, char **argv)
   if (executed)
   {
     if (result)
-      std::cout << "Response: [" << rep.data() << "]" << std::endl;
+      std::cout << "Response: " << std::endl;
     else
       std::cout << "Service call failed" << std::endl;
   }
diff --git a/example/responser_no_input.cc b/example/responser_no_input.cc
index f854151b..190dcc91 100644
--- a/example/responser_no_input.cc
+++ b/example/responser_no_input.cc
@@ -23,17 +23,8 @@
 //////////////////////////////////////////////////
 /// \brief Provide a "quote" service.
 /// Well OK, it's just single-quote service but do you really need more?
-bool srvQuote(ignition::msgs::StringMsg &_rep)
+bool srvQuote(ignition::msgs::Empty &_rep)
 {
-  std::string awesomeQuote = "This is it! This is the answer. It says here..."
-    "that a bolt of lightning is going to strike the clock tower at precisely "
-    "10:04pm, next Saturday night! If...If we could somehow...harness this "
-    "lightning...channel it...into the flux capacitor...it just might work. "
-    "Next Saturday night, we're sending you back to the future!";
-
-  // Set the response's content.
-  _rep.set_data(awesomeQuote);
-
   // The response succeed.
   return true;
 }
```

</p>
</details>

The `Empty` message has special meaning inside `ign-transport`. Maybe the problem is coming from here:

https://github.com/ignitionrobotics/ign-transport/blob/729e86c27207680b2df1eb5e5606332da8a1b806/src/NodeShared.cc#L671-L676

I guess we never thought there would be a use case for an empty request with an empty response. Maybe it could be useful to ping a node?

**Comment by adlarkin** [comment]
> I guess we never thought there would be a use case for an empty request with an empty response. Maybe it could be useful to ping a node?

In my case, I am using a service to set a flag that changes the state of the system I'm working with. So, I don't need a request since the service only does one thing (i.e., the behavior doesn't depend on the request information), and I don't really need a response either because if the service executes (which means it returns true), then the flag was set, so I don't have a need for a response (a response would just be duplicate information). What I'm doing for now is using a response of type `ignition::msgs::Boolean` and always setting it to true so I don't get a timeout, but like I said, this is redundant since the service call returns true if it succeeds. Maybe I should have been using a response of `ignition::msgs::Boolean` all along, but like I said, I never have any use for the response of the service I'm calling.
